### ISSUE TITLE
rqt 2.0 Issues list

### ISSUE THREAD

**Issue by danipurwadi** [yonahbox/Yonah_ROS_packages#43]
- [x] Syncing status bar for each aircraft. Status for each aircraft add to the waypoint side
- [x] Button for manual sync
- [x] Interface to add valid IDs (same as the launch file)

**Comment by disgruntled-patzer** [comment]
Error thrown by rqt during testing of multi-aircraft link switching:
```
Traceback (most recent call last):
  File "/home/lenovo/Yonah_ROS_packages/ogc_ws/src/yonah_rqt/src/yonah_rqt/main_window.py", line 371, in ondemand_display
    self.aircrafts_info.get("AC" + aircraft_id).statustext.appendPlainText(text_to_display)
AttributeError: 'NoneType' object has no attribute 'statustext'
```
The error is thrown when:

1. Receiving an incoming on-demand payload from aircraft (e.g. "h 1 5 HB 1603200000")
2. Sending an arm command

**Comment by disgruntled-patzer** [comment]
Issues with upgraded RQT on 22 Dec 2020:

Context: GCS 3 sending to Aircraft 2

When sending an arm command, the following error is thrown:

```
Traceback (most recent call last):
  File "/home/lenovo/Yonah_ROS_packages/ogc_ws/src/yonah_rqt/src/yonah_rqt/command_window.py", line 284, in arm
    if self.checklist_info.get("AC" + str(self.destination_id)).checklist_state == 0:
AttributeError: 'NoneType' object has no attribute 'checklist_state'
```

When sending a disarm or go command to Aircraft 2, the system sees it as trying to send to Aircraft 1, which throws an "Invalid Message" error:

```
[ERROR] [1608692886.420999]: Error: Invalid Aircraft ID
[INFO] [1608692886.425613]: data: "i 1 1 0 Invalid Aircraft ID. Command mode 10 not sent 1608692886"
Traceback (most recent call last):
  File "/home/lenovo/Yonah_ROS_packages/ogc_ws/src/yonah_rqt/src/yonah_rqt/main_window.py", line 378, in ondemand_display
    self.aircrafts_info.get("AC" + aircraft_id).statustext.appendPlainText(text_to_display)
AttributeError: 'NoneType' object has no attribute 'statustext'
```
